### ISSUE TITLE
Skip custom properties

### ISSUE THREAD

**Issue by rohit-gohri** [cdwv/oas3-api-snippet-enricher#12]
I am using [openapi-filter](https://github.com/Mermade/openapi-filter) to filter some paths, due to which methods have invalid boolean properties and this error is thrown:

```
TypeError: Cannot create property 'x-codeSamples' on boolean 'true'
    at enrichSchema (/Users/rohitgohri/.npm/_npx/85039/lib/node_modules/snippet-enricher-cli/index.js:19:48)
    at Object.<anonymous> (/Users/rohitgohri/.npm/_npx/85039/lib/node_modules/snippet-enricher-cli/index.js:40:12)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rohitgohri/.npm/_npx/85039/lib/node_modules/snippet-enricher-cli/bin/snippet-enricher-cli:2:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```

If we could skip `x-` properties in the loop this will be fixed.

**Comment by majidkarimizadeh** [comment]
any update? @KarolNet @andrzejwp @RolphH
