### ISSUE TITLE
TypeError: Cannot create property 'x-codeSamples' on string 'paths/pets.yaml'

### ISSUE THREAD

**Issue by timganter** [cdwv/oas3-api-snippet-enricher#17]
👋 Hello! 

Trying this out for the first time. I rearranged the [expanded petstore example](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore-expanded.yaml) to have...

```yaml
paths:
  /pets:
    $ref: paths/pets.yaml
```

Here is the directory for the rearranged petstore example. 

👉 [petstore.zip](https://github.com/cdwv/oas3-api-snippet-enricher/files/8240296/petstore.zip)

When I run `./node_modules/.bin/snippet-enricher-cli --input=petstore/openapi.yaml > openapi-with-examples.json`

I open up `openapi-with-examples.json` and it contains the following...

```bash
TypeError: Cannot create property 'x-codeSamples' on string 'paths/pets.yaml'
    at enrichSchema ({MY_LOCAL_PATH}/node_modules/snippet-enricher-cli/index.js:19:48)
    at Object.<anonymous> ({MY_LOCAL_PATH}/node_modules/snippet-enricher-cli/index.js:40:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> ({MY_LOCAL_PATH}/node_modules/snippet-enricher-cli/bin/snippet-enricher-cli:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

🤔 Does this not work on refs? Does the openapi.yaml need to be a single file?

**Comment by mniemcewicz** [comment]
This issue has been fixed with #19.
