### ISSUE TITLE
Error when secDefinition does not exists

### ISSUE THREAD

**Issue by RolphH** [cdwv/oas3-api-snippet-enricher#8]
When you parse OAS3 files without secDefintion.scheme, the script will fail. Opeapi-to-har expects a scheme.

```
 authScheme = secDefinition.scheme.toLowerCase();
                                          ^
TypeError: Cannot read property 'toLowerCase' of undefined
at getHeadersArray (/node_modules/openapi-snippet/openapi-to-har.js:287:43)
    at Object.createHar [as getEndpoint] (//node_modules/openapi-snippet/openapi-to-har.js:44:14)
    at Object.getEndpointSnippets (/node_modules/openapi-snippet/index.js:31:28)
    at enrichSchema (/node_modules/snippet-enricher-cli/index.js:18:39)
    at fs.readFile (node_modules/snippet-enricher-cli/index.js:52:12)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by andrzejwp** [comment]
True, although I'm not sure if this is something that we should be fixing inside this repo, as it's only a thin wrapper for ErikWittern/openapi-snippet.

We've hit a similar issue for API key schemes when integrating this into [Flotiq's user API docs](https://flotiq.com/docs/API/dynamic-content-api/) and [filed a PR](https://github.com/ErikWittern/openapi-snippet/pull/34) against ErikWittern/openapi-snippet. I believe you already traced that yours is a similar case and that there already is a PR for that in the respective repository.

**Comment by RolphH** [comment]
True found that issue. Will close it.
